repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.9
  hooks:
    # Update the uv lockfile
    - id: uv-lock
